# Generated by Django 6.0 on 2026-01-14 04:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='顧客ID')),
                ('name', models.CharField(max_length=200, verbose_name='顧客名')),
                ('postal_code', models.CharField(help_text='Format: 123-4567', max_length=8, verbose_name='郵便番号')),
                ('prefecture', models.CharField(help_text='例: 東京都、大阪府', max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('address', models.CharField(max_length=300, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prefecture'], name='idx_customer_prefecture'), models.Index(fields=['created_at'], name='idx_customer_created')],
            },
        ),
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='メーターID')),
                ('meter_number', models.CharField(max_length=50, unique=True, verbose_name='メーター番号')),
                ('installation_date', models.DateField(verbose_name='設置日')),
                ('meter_type', models.CharField(choices=[('residential', '住宅用'), ('commercial', '商業用'), ('industrial', '産業用')], default='residential', max_length=20, verbose_name='メータータイプ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='meters.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': 'スマートメーター',
                'verbose_name_plural': 'スマートメーター',
                'db_table': 'smart_meters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='読取ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='読取時刻')),
                ('kwh', models.DecimalField(decimal_places=3, help_text='Energy consumption in kWh', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='消費電力量 (kWh)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.smartmeter', verbose_name='メーター')),
            ],
            options={
                'verbose_name': 'メーター読取値',
                'verbose_name_plural': 'メーター読取値',
                'db_table': 'meter_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UsageAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='集計ID')),
                ('period_type', models.CharField(choices=[('daily', '日次'), ('monthly', '月次')], max_length=10, verbose_name='集計期間タイプ')),
                ('period_start', models.DateField(db_index=True, verbose_name='集計期間開始')),
                ('period_end', models.DateField(verbose_name='集計期間終了')),
                ('total_kwh', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='合計消費電力量 (kWh)')),
                ('avg_kwh', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='平均消費電力量 (kWh)')),
                ('peak_kwh', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='ピーク消費電力量 (kWh)')),
                ('off_peak_kwh', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='オフピーク消費電力量 (kWh)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='計算日時')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='meters.smartmeter', verbose_name='メーター')),
            ],
            options={
                'verbose_name': '使用量集計',
                'verbose_name_plural': '使用量集計',
                'db_table': 'usage_aggregates',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='smartmeter',
            index=models.Index(fields=['meter_number'], name='idx_meter_number'),
        ),
        migrations.AddIndex(
            model_name='smartmeter',
            index=models.Index(fields=['customer', 'is_active'], name='idx_meter_customer_active'),
        ),
        migrations.AddIndex(
            model_name='smartmeter',
            index=models.Index(fields=['meter_type'], name='idx_meter_type'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['meter', 'timestamp'], name='idx_reading_meter_time'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['timestamp'], name='idx_reading_timestamp'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['created_at'], name='idx_reading_created'),
        ),
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together={('meter', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='usageaggregate',
            index=models.Index(fields=['meter', 'period_type', 'period_start'], name='idx_agg_meter_period'),
        ),
        migrations.AddIndex(
            model_name='usageaggregate',
            index=models.Index(fields=['period_start'], name='idx_agg_period_start'),
        ),
        migrations.AlterUniqueTogether(
            name='usageaggregate',
            unique_together={('meter', 'period_type', 'period_start')},
        ),
    ]
