# Generated by Django 6.0 on 2026-01-14 04:30

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='メトリックID')),
                ('task_type', models.CharField(choices=[('django', 'Django 6.0 Tasks'), ('celery', 'Celery')], db_index=True, max_length=10, verbose_name='タスクタイプ')),
                ('task_name', models.CharField(db_index=True, max_length=200, verbose_name='タスク名')),
                ('task_id', models.CharField(blank=True, help_text='Original task ID from Django Tasks or Celery', max_length=200, null=True, verbose_name='タスクID')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='開始時刻')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了時刻')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='実行時間 (秒)')),
                ('records_processed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='処理レコード数')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the task execution', verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'タスクメトリック',
                'verbose_name_plural': 'タスクメトリック',
                'db_table': 'task_metrics',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_type', 'task_name'], name='idx_metric_type_name'), models.Index(fields=['started_at'], name='idx_metric_started'), models.Index(fields=['success'], name='idx_metric_success'), models.Index(fields=['task_type', 'success'], name='idx_metric_type_success')],
            },
        ),
    ]
